import json

# Colleges definition (100 colleges)
colleges_raw = [
  {"name": "IIT Bombay", "city": "Mumbai", "state": "Maharashtra", "category": "IIT", "website": "www.iitb.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Delhi", "city": "New Delhi", "state": "Delhi", "category": "IIT", "website": "home.iitd.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Madras", "city": "Chennai", "state": "Tamil Nadu", "category": "IIT", "website": "www.iitm.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Kanpur", "city": "Kanpur", "state": "Uttar Pradesh", "category": "IIT", "website": "www.iitk.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Kharagpur", "city": "Kharagpur", "state": "West Bengal", "category": "IIT", "website": "www.iitkgp.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Roorkee", "city": "Roorkee", "state": "Uttarakhand", "category": "IIT", "website": "www.iitr.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Guwahati", "city": "Guwahati", "state": "Assam", "category": "IIT", "website": "www.iitg.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Hyderabad", "city": "Hyderabad", "state": "Telangana", "category": "IIT", "website": "www.iith.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT (BHU) Varanasi", "city": "Varanasi", "state": "Uttar Pradesh", "category": "IIT", "website": "iitbhu.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Indore", "city": "Indore", "state": "Madhya Pradesh", "category": "IIT", "website": "www.iiti.ac.in", "featured": True, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT (ISM) Dhanbad", "city": "Dhanbad", "state": "Jharkhand", "category": "IIT", "website": "www.iitism.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Bhubaneswar", "city": "Bhubaneswar", "state": "Odisha", "category": "IIT", "website": "www.iitbbs.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Mandi", "city": "Mandi", "state": "Himachal Pradesh", "category": "IIT", "website": "www.iitmandi.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Gandhinagar", "city": "Gandhinagar", "state": "Gujarat", "category": "IIT", "website": "iitgn.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Jodhpur", "city": "Jodhpur", "state": "Rajasthan", "category": "IIT", "website": "iitj.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Patna", "city": "Patna", "state": "Bihar", "category": "IIT", "website": "www.iitp.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Ropar", "city": "Rupnagar", "state": "Punjab", "category": "IIT", "website": "www.iitrpr.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Tirupati", "city": "Tirupati", "state": "Andhra Pradesh", "category": "IIT", "website": "www.iittp.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Palakkad", "city": "Palakkad", "state": "Kerala", "category": "IIT", "website": "iitpkd.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Bhilai", "city": "Bhilai", "state": "Chhattisgarh", "category": "IIT", "website": "www.iitbhilai.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Goa", "city": "Ponda", "state": "Goa", "category": "IIT", "website": "iitgoa.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Jammu", "city": "Jammu", "state": "Jammu & Kashmir", "category": "IIT", "website": "iitjammu.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIT Dharwad", "city": "Dharwad", "state": "Karnataka", "category": "IIT", "website": "www.iitdh.ac.in", "featured": False, "avg": 12, "high": 50, "courses": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.5, "maxF": 3.0},
  {"name": "IIM Ahmedabad", "city": "Ahmedabad", "state": "Gujarat", "category": "IIM", "website": "www.iima.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Bangalore", "city": "Bengaluru", "state": "Karnataka", "category": "IIM", "website": "www.iimb.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Calcutta", "city": "Kolkata", "state": "West Bengal", "category": "IIM", "website": "www.iimcal.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Lucknow", "city": "Lucknow", "state": "Uttar Pradesh", "category": "IIM", "website": "www.iiml.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Kozhikode", "city": "Kozhikode", "state": "Kerala", "category": "IIM", "website": "iimk.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Indore", "city": "Indore", "state": "Madhya Pradesh", "category": "IIM", "website": "iimidr.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Shillong", "city": "Shillong", "state": "Meghalaya", "category": "IIM", "website": "www.iimshillong.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Rohtak", "city": "Rohtak", "state": "Haryana", "category": "IIM", "website": "www.iimrohtak.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Ranchi", "city": "Ranchi", "state": "Jharkhand", "category": "IIM", "website": "iimranchi.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Raipur", "city": "Raipur", "state": "Chhattisgarh", "category": "IIM", "website": "iimraipur.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Tiruchirappalli", "city": "Tiruchirappalli", "state": "Tamil Nadu", "category": "IIM", "website": "www.iimtrichy.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Udaipur", "city": "Udaipur", "state": "Rajasthan", "category": "IIM", "website": "www.iimu.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Kashipur", "city": "Kashipur", "state": "Uttarakhand", "category": "IIM", "website": "www.iimkashipur.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Nagpur", "city": "Nagpur", "state": "Maharashtra", "category": "IIM", "website": "www.iimnagpur.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Amritsar", "city": "Amritsar", "state": "Punjab", "category": "IIM", "website": "www.iimamritsar.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Bodh Gaya", "city": "Bodh Gaya", "state": "Bihar", "category": "IIM", "website": "iimbg.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Sambalpur", "city": "Sambalpur", "state": "Odisha", "category": "IIM", "website": "iimsambalpur.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Sirmaur", "city": "Sirmaur", "state": "Himachal Pradesh", "category": "IIM", "website": "www.iimsirmaur.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Visakhapatnam", "city": "Visakhapatnam", "state": "Andhra Pradesh", "category": "IIM", "website": "www.iimv.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Jammu", "city": "Jammu", "state": "Jammu & Kashmir", "category": "IIM", "website": "www.iimj.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "IIM Mumbai", "city": "Mumbai", "state": "Maharashtra", "category": "IIM", "website": "iimmumbai.ac.in", "featured": False, "avg": 15, "high": 40, "courses": "MBA, Executive MBA, Ph.D., Management Programs", "minF": 7.0, "maxF": 25.0},
  {"name": "AIIMS New Delhi", "city": "New Delhi", "state": "Delhi", "category": "AIIMS", "website": "www.aiims.edu", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Bhopal", "city": "Bhopal", "state": "Madhya Pradesh", "category": "AIIMS", "website": "www.aiimsbhopal.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Bhubaneswar", "city": "Bhubaneswar", "state": "Odisha", "category": "AIIMS", "website": "aiimsbhubaneswar.nic.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Jodhpur", "city": "Jodhpur", "state": "Rajasthan", "category": "AIIMS", "website": "www.aiimsjodhpur.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Patna", "city": "Patna", "state": "Bihar", "category": "AIIMS", "website": "aiimspatna.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Raipur", "city": "Raipur", "state": "Chhattisgarh", "category": "AIIMS", "website": "www.aiimsraipur.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Rishikesh", "city": "Rishikesh", "state": "Uttarakhand", "category": "AIIMS", "website": "aiimsrishikesh.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Raebareli", "city": "Raebareli", "state": "Uttar Pradesh", "category": "AIIMS", "website": "aiimsrbl.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Gorakhpur", "city": "Gorakhpur", "state": "Uttar Pradesh", "category": "AIIMS", "website": "aiimsgorakhpur.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Mangalagiri", "city": "Mangalagiri", "state": "Andhra Pradesh", "category": "AIIMS", "website": "aiimsmangalagiri.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Nagpur", "city": "Nagpur", "state": "Maharashtra", "category": "AIIMS", "website": "aiimsnagpur.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Bathinda", "city": "Bathinda", "state": "Punjab", "category": "AIIMS", "website": "aiimsbathinda.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Bibinagar", "city": "Bibinagar", "state": "Telangana", "category": "AIIMS", "website": "aiimsbibinagar.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Kalyani", "city": "Kalyani", "state": "West Bengal", "category": "AIIMS", "website": "aiimskalyani.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Deoghar", "city": "Deoghar", "state": "Jharkhand", "category": "AIIMS", "website": "aiimsdeoghar.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Bilaspur", "city": "Bilaspur", "state": "Himachal Pradesh", "category": "AIIMS", "website": "aiimsbilaspur.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Rajkot", "city": "Rajkot", "state": "Gujarat", "category": "AIIMS", "website": "aiimsrajkot.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Guwahati", "city": "Guwahati", "state": "Assam", "category": "AIIMS", "website": "aiimsguwahati.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Jammu", "city": "Vijaypur", "state": "Jammu & Kashmir", "category": "AIIMS", "website": "www.aiimsjammu.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Madurai", "city": "Madurai", "state": "Tamil Nadu", "category": "AIIMS", "website": "www.aiimsmadurai.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Darbhanga", "city": "Darbhanga", "state": "Bihar", "category": "AIIMS", "website": "aiimsdarbhanga.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "AIIMS Rewari", "city": "Majra, Rewari", "state": "Haryana", "category": "AIIMS", "website": "aiimsrewari.edu.in", "featured": False, "avg": 0, "high": 0, "courses": "MBBS, MD/MS, DM/MCh, Nursing, Allied Health, Ph.D.", "minF": 0.2, "maxF": 1.5},
  {"name": "IISER Pune", "city": "Pune", "state": "Maharashtra", "category": "IISER", "website": "www.iiserpune.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Kolkata", "city": "Kolkata", "state": "West Bengal", "category": "IISER", "website": "www.iiserkol.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Mohali", "city": "Sahibzada Ajit Singh Nagar", "state": "Punjab", "category": "IISER", "website": "www.iisermohali.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Bhopal", "city": "Bhopal", "state": "Madhya Pradesh", "category": "IISER", "website": "www.iiserb.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Thiruvananthapuram", "city": "Thiruvananthapuram", "state": "Kerala", "category": "IISER", "website": "www.iisertvm.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Tirupati", "city": "Tirupati", "state": "Andhra Pradesh", "category": "IISER", "website": "www.iisertirupati.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "IISER Berhampur", "city": "Berhampur", "state": "Odisha", "category": "IISER", "website": "www.iiserbpr.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS-MS, MS, Ph.D., Integrated and Research Programs", "minF": 0.3, "maxF": 1.5},
  {"name": "Indian Institute of Science (IISc)", "city": "Bengaluru", "state": "Karnataka", "category": "Research Institute", "website": "iisc.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS/Integrated Programs, M.Tech/M.Sc, Ph.D., Research Programs", "minF": 0.2, "maxF": 2.0},
  {"name": "Indian Statistical Institute (ISI)", "city": "Kolkata", "state": "West Bengal", "category": "Research Institute", "website": "www.isical.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS/Integrated Programs, M.Tech/M.Sc, Ph.D., Research Programs", "minF": 0.2, "maxF": 2.0},
  {"name": "National Institute of Science Education and Research (NISER)", "city": "Bhubaneswar", "state": "Odisha", "category": "Research Institute", "website": "www.niser.ac.in", "featured": False, "avg": 0, "high": 0, "courses": "BS/Integrated Programs, M.Tech/M.Sc, Ph.D., Research Programs", "minF": 0.2, "maxF": 2.0},
  {"name": "NIT Trichy", "city": "Tiruchirappalli", "state": "Tamil Nadu", "category": "NIT", "website": "www.nitt.edu", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Rourkela", "city": "Rourkela", "state": "Odisha", "category": "NIT", "website": "nitrkl.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Surathkal", "city": "Mangaluru", "state": "Karnataka", "category": "NIT", "website": "www.nitk.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Warangal", "city": "Warangal", "state": "Telangana", "category": "NIT", "website": "www.nitw.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Calicut", "city": "Kozhikode", "state": "Kerala", "category": "NIT", "website": "nitc.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "MNNIT Allahabad", "city": "Prayagraj", "state": "Uttar Pradesh", "category": "NIT", "website": "www.mnnit.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Kurukshetra", "city": "Kurukshetra", "state": "Haryana", "category": "NIT", "website": "nitkkr.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Durgapur", "city": "Durgapur", "state": "West Bengal", "category": "NIT", "website": "nitdgp.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Silchar", "city": "Silchar", "state": "Assam", "category": "NIT", "website": "www.nits.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Hamirpur", "city": "Hamirpur", "state": "Himachal Pradesh", "category": "NIT", "website": "nith.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Jalandhar", "city": "Jalandhar", "state": "Punjab", "category": "NIT", "website": "www.nitj.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "MNIT Jaipur", "city": "Jaipur", "state": "Rajasthan", "category": "NIT", "website": "www.mnit.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Patna", "city": "Patna", "state": "Bihar", "category": "NIT", "website": "www.nitp.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Raipur", "city": "Raipur", "state": "Chhattisgarh", "category": "NIT", "website": "nitrr.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Srinagar", "city": "Srinagar", "state": "Jammu & Kashmir", "category": "NIT", "website": "nitsri.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Agartala", "city": "Agartala", "state": "Tripura", "category": "NIT", "website": "nita.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Goa", "city": "Ponda", "state": "Goa", "category": "NIT", "website": "www.nitgoa.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Meghalaya", "city": "Shillong", "state": "Meghalaya", "category": "NIT", "website": "www.nitm.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Manipur", "city": "Imphal", "state": "Manipur", "category": "NIT", "website": "nitmanipur.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Mizoram", "city": "Aizawl", "state": "Mizoram", "category": "NIT", "website": "www.nitmz.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Nagaland", "city": "Dimapur", "state": "Nagaland", "category": "NIT", "website": "nitnagaland.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Arunachal Pradesh", "city": "Yupia", "state": "Arunachal Pradesh", "category": "NIT", "website": "www.nitap.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Delhi", "city": "New Delhi", "state": "Delhi", "category": "NIT", "website": "nitdelhi.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5},
  {"name": "NIT Puducherry", "city": "Karaikal", "state": "Puducherry", "category": "NIT", "website": "www.nitpy.ac.in", "featured": False, "avg": 8, "high": 30, "courses": "B.Tech, M.Tech, M.Sc, MBA, Ph.D.", "minF": 0.8, "maxF": 2.5}
]

final_colleges = []
for idx, c in enumerate(colleges_raw):
    site = c["website"]
    icon_url = f"https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252F{site}%26sz%3D256&output=jpg&q=95"
    final_colleges.append({
        "id": idx + 1,
        "name": c["name"],
        "nameKn": c["name"],
        "city": c["city"],
        "state": c["state"],
        "location": f"{c['city']}, {c['state']}",
        "locationKn": f"{c['city']}, {c['state']}",
        "category": c["category"],
        "coursesOffered": c["courses"],
        "coursesOfferedKn": c["courses"],
        "eligibility": "12th with PCM/PCB as applicable; entrance exam / national criteria",
        "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
        "admissionStatus": "Varies by program",
        "featured": c["featured"],
        "isFeatured": c["featured"],
        "heroBannerUrl": icon_url,
        "imageUrl": icon_url,
        "averagePackageLakhs": float(c["avg"]),
        "highestPackageLakhs": float(c["high"]),
        "hostelAvailable": True,
        "hostelFeesPerYear": 60000 if c["category"] != "IIM" else 100000,
        "minFeesLakhs": c["minF"],
        "maxFeesLakhs": c["maxF"],
        "overview": f"{c['name']} is a premier national public institution situated in {c['city']}, {c['state']} offering top academic programs and research facilities.",
        "overviewKn": f"{c['name']} ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
        "ranking": idx + 1,
        "recognition": "Government of India / Institution of National Importance",
        "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
        "websiteUrl": f"https://{site}"
    })

with open("app/src/main/assets/colleges.json", "w", encoding="utf-8") as f:
    json.dump(final_colleges, f, indent=2, ensure_ascii=False)

print(f"Successfully wrote {len(final_colleges)} colleges to colleges.json")
