# Script to write the user's updated courses JSON to assets
import json

raw_json = """[
  {
    "id": 1,
    "title": "MBBS / Doctor",
    "titleKn": "ವೈದ್ಯರು",
    "category": "Medical",
    "benefits": "• Strong career opportunities • Practical and transferable skills • Opportunities across India and global markets • Multiple specialization and higher-study pathways",
    "benefitsKn": "• ಉತ್ತಮ ವೃತ್ತಿ ಅವಕಾಶಗಳು • ಪ್ರಾಯೋಗಿಕ ಮತ್ತು ಅನ್ವಯಿಸಬಹುದಾದ ಕೌಶಲ್ಯಗಳು • ಭಾರತ ಮತ್ತು ಜಾಗತಿಕ ಮಾರುಕಟ್ಟೆಗಳಲ್ಲಿ ಅವಕಾಶಗಳು • ವಿಶೇಷೀಕರಣ ಮತ್ತು ಉನ್ನತ ಶಿಕ್ಷಣದ ಹಲವು ಮಾರ್ಗಗಳು",
    "certifications": "Degree/Diploma Certificate, professional registration or role-specific certifications where applicable",
    "certificationsKn": "ಪದವಿ/ಡಿಪ್ಲೊಮಾ ಪ್ರಮಾಣಪತ್ರ, ಅನ್ವಯಿಸುವ ವೃತ್ತಿಪರ ನೋಂದಣಿ ಅಥವಾ ಕ್ಷೇತ್ರ-ನಿರ್ದಿಷ್ಟ ಪ್ರಮಾಣಪತ್ರಗಳು",
    "description": "The MBBS / Doctor pathway develops specialized knowledge and practical skills for careers in healthcare.",
    "descriptionKn": "MBBS / ವೈದ್ಯರು ಕಾರ್ಯಕ್ರಮವು ಅಗತ್ಯ ಜ್ಞಾನ, ಪ್ರಾಯೋಗಿಕ ಕೌಶಲ್ಯ ಮತ್ತು ವೃತ್ತಿ ಅವಕಾಶಗಳಿಗೆ ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಸಿದ್ಧಗೊಳಿಸುತ್ತದೆ.",
    "duration": "5.5 Years",
    "eligibility": "12th Science with PCB; NEET UG",
    "eligibilityKn": "12ನೇ ತರಗತಿ ವಿಜ್ಞಾನ with PCB; NEET UG",
    "exams": "NEET UG, NEET PG / NEXT, USMLE, PLAB",
    "examsKn": "NEET UG, NEET PG / NEXT, USMLE, PLAB",
    "faqs": "Q: What is the duration? A: 5.5 Years. Q: What is the eligibility? A: 12th Science with PCB; NEET UG. Q: Are requirements identical everywhere? A: No, they vary by institution, state and regulator.",
    "faqsKn": "ಪ್ರಶ್ನೆ: ಕೋರ್ಸ್‌ನ ಅವಧಿ ಎಷ್ಟು? ಉತ್ತರ: 5.5 Years. ಪ್ರಶ್ನೆ: ಅರ್ಹತೆ ಏನು? ಉತ್ತರ: 12th Science with PCB; NEET UG.",
    "feesAverage": "₹ 50,000 - 15 Lakhs / Year",
    "futureScope": "Future opportunities are supported by continued growth, technology adoption and demand for skilled professionals in healthcare.",
    "futureScopeKn": "healthcare ಕ್ಷೇತ್ರದ ಬೆಳವಣಿಗೆ, ತಂತ್ರಜ್ಞಾನ ಬಳಕೆ ಮತ್ತು ಕೌಶಲ್ಯಪೂರ್ಣ ವೃತ್ತಿಪರರ ಬೇಡಿಕೆಯಿಂದ ಭವಿಷ್ಯದಲ್ಲಿ ಉತ್ತಮ ಅವಕಾಶಗಳಿವೆ.",
    "jobRoles": "Professional, Specialist, Analyst, Coordinator, Consultant, Research Associate",
    "jobRolesKn": "ವೃತ್ತಿಪರ, ತಜ್ಞ, ವಿಶ್ಲೇಷಕ, ಸಂಯೋಜಕ, ಸಲಹೆಗಾರ, ಸಂಶೋಧನಾ ಸಹಾಯಕ",
    "opportunities": "Government organizations, private companies, specialist firms, research institutions, startups and service organizations",
    "opportunitiesKn": "ಸರ್ಕಾರಿ ಸಂಸ್ಥೆಗಳು, ಖಾಸಗಿ ಕಂಪನಿಗಳು, ವಿಶೇಷ ಸಂಸ್ಥೆಗಳು, ಸಂಶೋಧನಾ ಸಂಸ್ಥೆಗಳು, ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು ಮತ್ತು ಸೇವಾ ಸಂಸ್ಥೆಗಳು",
    "overview": "MBBS / Doctor is a career-focused pathway combining foundational learning, practical exposure and specialization opportunities.",
    "overviewKn": "MBBS / ವೈದ್ಯರು ಮೂಲಭೂತ ಜ್ಞಾನ, ಪ್ರಾಯೋಗಿಕ ಕಲಿಕೆ ಮತ್ತು ವಿಶೇಷೀಕರಣದ ಅವಕಾಶಗಳನ್ನು ಒದಗಿಸುವ ವೃತ್ತಿ ಕೇಂದ್ರೀಕೃತ ಮಾರ್ಗವಾಗಿದೆ.",
    "pathway": "Step 1: Complete the required school qualification Step 2: Meet entrance/admission requirements Step 3: Complete the 5.5 Years program Step 4: Gain practical experience and relevant certifications Step 5: Start a career or pursue higher studies",
    "pathwayKn": "ಹಂತ 1: ಅಗತ್ಯ ಶಾಲಾ ಅರ್ಹತೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಹಂತ 2: ಪ್ರವೇಶ ನಿಯಮಗಳನ್ನು ಪೂರೈಸಿ ಹಂತ 3: 5.5 Years ಕಾರ್ಯಕ್ರಮವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಹಂತ 4: ಪ್ರಾಯೋಗಿಕ ಅನುಭವ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಪಡೆಯಿರಿ ಹಂತ 5: ಉದ್ಯೋಗ ಅಥವಾ ಉನ್ನತ ಶಿಕ್ಷಣ ಆಯ್ಕೆಮಾಡಿ",
    "salaryAverage": "₹ 3 - 12 Lakhs / Year",
    "salaryHighest": "₹ 20+ Lakhs / Year",
    "scholarships": "National/state merit scholarships, institution scholarships and eligible government schemes",
    "scholarshipsKn": "ರಾಷ್ಟ್ರೀಯ/ರಾಜ್ಯ ಮೆರಿಟ್ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು, ಸಂಸ್ಥೆಯ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಮತ್ತು ಅರ್ಹ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    "skills": "Critical Thinking, Communication, Problem Solving, Teamwork, Professional Skills",
    "skillsKn": "ವಿಮರ್ಶಾತ್ಮಕ ಚಿಂತನೆ, ಸಂವಹನ, ಸಮಸ್ಯೆ ಪರಿಹಾರ, ತಂಡದ ಕೆಲಸ, ವೃತ್ತಿಪರ ಕೌಶಲ್ಯಗಳು",
    "subjects": "Core fundamentals, specialization subjects, practical learning, projects and professional practice",
    "subjectsKn": "ಮೂಲಭೂತ ವಿಷಯಗಳು, ವಿಶೇಷೀಕರಣ ವಿಷಯಗಳು, ಪ್ರಾಯೋಗಿಕ ಕಲಿಕೆ, ಯೋಜನೆಗಳು ಮತ್ತು ವೃತ್ತಿಪರ ಅಭ್ಯಾಸ",
    "tagline": "Build expertise and a rewarding career in MBBS / Doctor",
    "taglineKn": "MBBS / ವೈದ್ಯರು ಕ್ಷೇತ್ರದಲ್ಲಿ ಕೌಶಲ್ಯ ಬೆಳೆಸಿ ಉತ್ತಮ ವೃತ್ತಿ ನಿರ್ಮಿಸಿ",
    "whyChoose": "Strong career relevance, practical skill development, industry opportunities and long-term growth potential in healthcare.",
    "whyChooseKn": "ವೃತ್ತಿಗೆ ನೇರ ಸಂಬಂಧ, ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ, ಉದ್ಯಮದ ಅವಕಾಶಗಳು ಮತ್ತು healthcare ಕ್ಷೇತ್ರದಲ್ಲಿ ದೀರ್ಘಕಾಲೀನ ಬೆಳವಣಿಗೆ.",
    "topColleges": "Leading universities, government institutions, autonomous colleges and specialized institutes",
    "topCollegesKn": "ಪ್ರಮುಖ ವಿಶ್ವವಿದ್ಯಾಲಯಗಳು, ಸರ್ಕಾರಿ ಸಂಸ್ಥೆಗಳು, ಸ್ವಾಯತ್ತ ಕಾಲೇಜುಗಳು ಮತ್ತು ವಿಶೇಷ ಸಂಸ್ಥೆಗಳು",
    "topRecruiters": "Leading employers, government organizations, multinational companies, startups and sector-specific organizations",
    "topRecruitersKn": "ಪ್ರಮುಖ ಉದ್ಯೋಗದಾತರು, ಸರ್ಕಾರಿ ಸಂಸ್ಥೆಗಳು, ಬಹುರಾಷ್ಟ್ರೀಯ ಕಂಪನಿಗಳು, ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು ಮತ್ತು ಕ್ಷೇತ್ರ-ನಿರ್ದಿಷ್ಟ ಸಂಸ್ಥೆಗಳು",
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Professional%20medical%20doctor.jpg"
  }
]"""
