import json

# Write colleges.json (100 colleges from user prompt)
colleges_data = [
  {
    "id": 1,
    "name": "IIT Bombay",
    "nameKn": "IIT Bombay",
    "city": "Mumbai",
    "state": "Maharashtra",
    "location": "Mumbai, Maharashtra",
    "locationKn": "Mumbai, Maharashtra",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitb.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitb.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Bombay is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Bombay ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 1,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitb.ac.in"
  },
  {
    "id": 2,
    "name": "IIT Delhi",
    "nameKn": "IIT Delhi",
    "city": "New Delhi",
    "state": "Delhi",
    "location": "New Delhi, Delhi",
    "locationKn": "New Delhi, Delhi",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fhome.iitd.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fhome.iitd.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Delhi is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Delhi ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 2,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://home.iitd.ac.in"
  },
  {
    "id": 3,
    "name": "IIT Madras",
    "nameKn": "IIT Madras",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "location": "Chennai, Tamil Nadu",
    "locationKn": "Chennai, Tamil Nadu",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitm.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitm.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Madras is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Madras ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 3,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitm.ac.in"
  },
  {
    "id": 4,
    "name": "IIT Kanpur",
    "nameKn": "IIT Kanpur",
    "city": "Kanpur",
    "state": "Uttar Pradesh",
    "location": "Kanpur, Uttar Pradesh",
    "locationKn": "Kanpur, Uttar Pradesh",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitk.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitk.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Kanpur is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Kanpur ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 4,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitk.ac.in"
  },
  {
    "id": 5,
    "name": "IIT Kharagpur",
    "nameKn": "IIT Kharagpur",
    "city": "Kharagpur",
    "state": "West Bengal",
    "location": "Kharagpur, West Bengal",
    "locationKn": "Kharagpur, West Bengal",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitkgp.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitkgp.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Kharagpur is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Kharagpur ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 5,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitkgp.ac.in"
  },
  {
    "id": 6,
    "name": "IIT Roorkee",
    "nameKn": "IIT Roorkee",
    "city": "Roorkee",
    "state": "Uttarakhand",
    "location": "Roorkee, Uttarakhand",
    "locationKn": "Roorkee, Uttarakhand",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitr.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitr.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Roorkee is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Roorkee ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 6,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitr.ac.in"
  },
  {
    "id": 7,
    "name": "IIT Guwahati",
    "nameKn": "IIT Guwahati",
    "city": "Guwahati",
    "state": "Assam",
    "location": "Guwahati, Assam",
    "locationKn": "Guwahati, Assam",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitg.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iitg.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Guwahati is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Guwahati ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 7,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iitg.ac.in"
  },
  {
    "id": 8,
    "name": "IIT Hyderabad",
    "nameKn": "IIT Hyderabad",
    "city": "Hyderabad",
    "state": "Telangana",
    "location": "Hyderabad, Telangana",
    "locationKn": "Hyderabad, Telangana",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iith.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iith.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Hyderabad is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Hyderabad ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 8,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iith.ac.in"
  },
  {
    "id": 9,
    "name": "IIT (BHU) Varanasi",
    "nameKn": "IIT (BHU) Varanasi",
    "city": "Varanasi",
    "state": "Uttar Pradesh",
    "location": "Varanasi, Uttar Pradesh",
    "locationKn": "Varanasi, Uttar Pradesh",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fiitbhu.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fiitbhu.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT (BHU) Varanasi is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT (BHU) Varanasi ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 9,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://iitbhu.ac.in"
  },
  {
    "id": 10,
    "name": "IIT Indore",
    "nameKn": "IIT Indore",
    "city": "Indore",
    "state": "Madhya Pradesh",
    "location": "Indore, Madhya Pradesh",
    "locationKn": "Indore, Madhya Pradesh",
    "category": "IIT",
    "coursesOffered": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "coursesOfferedKn": "B.Tech, B.S., M.Tech, M.Sc, MBA, Ph.D.",
    "eligibility": "12th with PCM/PCB as applicable; JEE Advanced/JEE Main or program-specific criteria",
    "eligibilityKn": "ಕಾರ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಅರ್ಹತೆ ಬದಲಾಗುತ್ತದೆ; ಸಂಬಂಧಿತ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಮತ್ತು ಸಂಸ್ಥೆಯ ನಿಯಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "admissionStatus": "Varies by program",
    "featured": True,
    "heroBannerUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iiti.ac.in%26sz%3D256&output=jpg&q=95",
    "imageUrl": "https://images.weserv.nl/?url=https%3A%2F%2Fwww.google.com%2Fs2%2Ffavicons%3Fdomain_url%3Dhttps%253A%252F%252Fwww.iiti.ac.in%26sz%3D256&output=jpg&q=95",
    "averagePackageLakhs": 12.0,
    "highestPackageLakhs": 50.0,
    "hostelAvailable": True,
    "hostelFeesPerYear": 60000,
    "minFeesLakhs": 0.5,
    "maxFeesLakhs": 3.0,
    "overview": "IIT Indore is a prominent public institution offering nationally recognized programs in its academic and professional fields.",
    "overviewKn": "IIT Indore ಪ್ರಮುಖ ಸರ್ಕಾರಿ/ಸಾರ್ವಜನಿಕ ಉನ್ನತ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಯಾಗಿದ್ದು ವಿವಿಧ ಶೈಕ್ಷಣಿಕ ಮತ್ತು ವೃತ್ತಿಪರ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    "ranking": 10,
    "recognition": "Government of India / Institution of National Importance",
    "recognitionKn": "ಭಾರತ ಸರ್ಕಾರದ ಮಾನ್ಯತೆ/ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸಂಸ್ಥೆ",
    "websiteUrl": "https://www.iiti.ac.in"
  }
]
